# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: report-on-vulnerabilities

permissions: {}

on:
  workflow_dispatch: {}
  schedule:
    - cron: '23 2 * * *' # Every day at 02:23

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  scan:
    runs-on: ubuntu-latest
    outputs:
      results: ${{ steps.parse-results.outputs.results }}
    steps:    
    - name: Get Branches Name
      id: get-branches
      run: |
        all_branches=$(curl -s 'https://api.github.com/repos/${{ env.IMAGE_NAME }}/branches?per_page=100' | jq -r '.[].name | select(startswith("release-"))' | sort -rV | head -n 2)
        releasebranch1=$(echo "$all_branches" | sed -n 1p)
        releasebranch2=$(echo "$all_branches" | sed -n 2p)

        echo "releasebranch1=$releasebranch1" >> $GITHUB_OUTPUT
        echo "releasebranch2=$releasebranch2" >> $GITHUB_OUTPUT
    
    - name: Scan for vulnerabilities in latest image
      id: scan-latest-image
      continue-on-error: true
      uses: aquasecurity/trivy-action@7c2007bcb556501da015201bcba5aa14069b74e2 # v0.8.0 (Trivy v0.34.0)
      with: 
        image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:ff88c4c39ac93939332a8601f4c7402dfad59309
        format: table
        exit-code: '1'
        ignore-unfixed: true
        severity: HIGH,CRITICAL
        output: scan.md

    - name: Scan for vulnerabilities in latest-1 image
      id: scan-latest1-image
      uses: aquasecurity/trivy-action@7c2007bcb556501da015201bcba5aa14069b74e2 # v0.8.0 (Trivy v0.34.0)
      continue-on-error: true
      with: 
        image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get-branches.outputs.releasebranch1 }}
        format: table
        exit-code: '1'
        ignore-unfixed: true
        severity: HIGH,CRITICAL
        output: scan1.md

    - name: Scan for vulnerabilities in latest-2 image
      id: scan-latest2-image
      uses: aquasecurity/trivy-action@7c2007bcb556501da015201bcba5aa14069b74e2 # v0.8.0 (Trivy v0.34.0)
      continue-on-error: true
      with: 
        image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get-branches.outputs.releasebranch2 }}
        format: table
        exit-code: '1'
        ignore-unfixed: true
        severity: HIGH,CRITICAL
        output: scan2.md

    - name: Merge scan results
      id: merge-results
      run: |
        cat scan.md scan1.md scan2.md > merged_scans.md

    - name: Parse scan results
      id: parse-results
      continue-on-error: true
      run: |
        if [[ ${{ steps.scan-latest-image.outcome }} -eq "failure" || ${{ steps.scan-latest1-image.outcome }} -eq "failure" ||  ${{ steps.scan-latest2-image.outcome }} -eq "failure" ]]
        then
          echo "Vulnerabilities found, creating issue"
          echo "results=found" >> $GITHUB_OUTPUT
        else
          echo "No vulnerabilities found, halting"
          echo "results=nothing" >> $GITHUB_OUTPUT
        fi

    - name: Upload vulnerability scan report
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      if: steps.parse-results.outputs.results == 'found'
      with:
        name: merged_scans.md
        path: merged_scans.md
        if-no-files-found: error

  open-issue:
    runs-on: ubuntu-latest
    if: needs.scan.outputs.results == 'found'
    needs: scan
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Download scan
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: merged_scans.md

      - name: Set scan output
        id: set-scan-output
        run: echo "results=$(cat merged_scans.md )" >> $GITHUB_OUTPUT
  
      - uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5 # v2.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RESULTS: ${{ steps.set-scan-output.outputs.results }}
        with:
          filename: .github/ISSUE_TEMPLATE/VULN-TEMPLATE.md
